### ISSUE TITLE
maintainer request

### ISSUE THREAD

**Issue by ror6ax** [ranmocy/guard-rails#37]
Hi guys, I would be happy to help on maintaining this.

Thibaud had adviced to open an issue here on this matter.
Thanks,
Gregory

**Comment by ranmocy** [comment]
Sorry for late replying.
Thank you for you asking to help on maintaining Guard-Rails. But this project has less meaning on development further nowadays since rails can already dynamic reload by itself. The initial purpose of Guard-Rails is more or less replaced. It even be removed from Guard official list. This project will only need compatibility maintenance in future. Not much work, but if you still want help, start a PullRequest and it's always welcomed.
Thanks again.
