### ISSUE TITLE
how to allow log to unlimited size

### ISSUE THREAD

**Issue by westonganger** [ranmocy/guard-rails#41]
It stops showing the log and starts only showing:

```
14:50:50 - INFO - Reloading browser: app/views/whatever/index.html.slim
```

Is there an option to disable logging limit? (or could this have to do with ghosting issues w/ zeus and guard)

**Comment by ranmocy** [comment]
There is no limit on log in `guard-rails` side. Guard-Rails run Rails with system call, which means it touch nothing but just run Rails directly like in your terminal.
Also, the log said `Reloading browser`, it's not a Guard-Rails output. It won't reload your browser. Do you use any rails plugin such as LiveReload?

**Comment by westonganger** [comment]
Yes I do have live reload which appears to be working correctly because it keeps showing even after the log stops. It just  seems odd that the only thing that stops showing is the rails log.  You don't think there's a memory limitation or something on the log?

**Comment by ranmocy** [comment]
If there is, it exists in Rails rather than Guard-Rails.
You can check this code: https://github.com/ranmocy/guard-rails/blob/master/lib/guard/rails/runner.rb#L108-L114
Since it just use system call, it should have no difference with running Rails in terminals.

Have you tried to start Rails directly in your terminal with exactly the same arguments?

**Comment by ranmocy** [comment]
Close it now. Reopen it if you have further questions.
