### ISSUE TITLE
guard-rails mysteriously restarting

### ISSUE THREAD

**Issue by istrasci** [ranmocy/guard-rails#46]
When I upgraded from rails-4.2.7.1 to 5.0.1, guard is mysteriously restarting itself for some reason.  See my [Stackoverflow post](http://stackoverflow.com/q/41412736/209107) for output and more detail.

**Comment by ranmocy** [comment]
As my test, the minimal buggy Guardfile looks like:
```ruby
guard 'rails'
guard 'yard'
```
The issue is that, for reason unknown, guard-yard stop and restart Puma server during starting. Which is the default dev server introduced in Rails 5.0. If rails has already started, it will kill the server and cause it to restart but failed.

What you need to do is simply swap them:
```ruby
guard 'yard'
guard 'rails'
```
In fact, I believe guard-yard should not kill rails server by all means.

**Comment by istrasci** [comment]
This appears to work.  Thank you!
